name: Validate PR Branches
on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  validate:
    if: github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'preview'
    env:
      source: ${{ github.event.pull_request.base.ref == 'main' && 'preview' || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check source and target
        if: ${{ github.event.pull_request.head.ref != env.source }}
        run: echo 'Cannot target branch ${{github.event.pull_request.base.ref}} from source branch ${{github.event.pull_request.head.ref}}' &&  exit 1