name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'
      - '!main'
      - '!preview'
jobs:
  validate:
    env:

      base: ${{ github.event.pull_request.base.ref }}
      head: ${{ github.event.pull_request.head.ref }}
      required_head: ${{ github.event.pull_request.base.ref == 'main' && 'preview' || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip validation
        if: ${{ github.action.pull_request.base.ref != 'main' && env.head != 'preview' }}
        run: echo 'Can point head branch ${{ env.head }} at base branch ${{ env.base }}' && exit 0
      - name: Check validation
        if: ${{ (env.base == 'main' || env.base == 'preview') && env.head != env.required_head }}
        run: echo 'Cannot point head branch ${{ env.head }} at base branch ${{ env.base }}' &&  exit 1
  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  preview:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Allow comments on PRs
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: npm
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm i
      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
          # Use your own, or keep the automatically infered branch name from `--auto`, when using different triggers.
          command: eas update --auto --branch=${{ github.event.pull_request.head.ref }}